/var/log/suffat-erp/*.log {
    daily
    missingok
    rotate 14
    compress
    delaycompress
    notifempty
    create 0640 www-data adm
    sharedscripts
    postrotate
        /bin/kill -HUP `cat /var/run/nginx.pid 2>/dev/null` 2>/dev/null || true
    endscript
}
