# Location: services/core-backend/tests/test_pdf_generation_concurrency.py
"""
Test: PDF Generation Correctness & Concurrency Safety
Validates that the ReportLab PDF generator produces valid PDFs
and handles concurrent invocations without data mixing.
"""
import pytest
import asyncio
from app.core.reports.pdf_generator import generate_progress_report_pdf
from app.core.reports.excel_generator import generate_financial_ledger_excel


class TestPDFGeneratorCorrectness:
    """Tests for PDF byte-stream generation."""

    def test_pdf_generates_valid_bytes(self):
        """Generated bytes must begin with PDF magic marker."""
        sabaq = [
            {"date": "2026-08-01", "juz_number": 1, "page_start": 1, "page_end": 5, "grade": "A"},
        ]
        result = generate_progress_report_pdf(
            student_name="Test Student",
            attendance=95.0,
            grade="A",
            sabaq_list=sabaq,
        )
        assert isinstance(result, bytes)
        assert len(result) > 0
        assert result[:5] == b"%PDF-"

    def test_pdf_contains_student_data(self):
        """The rendered PDF should contain student data (verify via size difference)."""
        sabaq_short = [
            {"date": "2026-08-10", "juz_number": 2, "page_start": 1, "page_end": 3, "grade": "B+"},
        ]
        sabaq_long = [
            {"date": f"2026-08-{i:02d}", "juz_number": i, "page_start": i, "page_end": i + 2, "grade": "A"}
            for i in range(1, 20)
        ]
        result_short = generate_progress_report_pdf(
            student_name="Short List Student",
            attendance=94.5,
            grade="A",
            sabaq_list=sabaq_short,
        )
        result_long = generate_progress_report_pdf(
            student_name="Long List Student",
            attendance=94.5,
            grade="A",
            sabaq_list=sabaq_long,
        )
        # More sabaq entries → larger PDF
        assert len(result_long) > len(result_short)

    def test_pdf_handles_empty_sabaq(self):
        """PDF generation should not crash with an empty sabaq list."""
        result = generate_progress_report_pdf(
            student_name="Empty Record Student",
            attendance=0.0,
            grade="N/A",
            sabaq_list=[],
        )
        assert isinstance(result, bytes)
        assert result[:5] == b"%PDF-"


class TestExcelGeneratorCorrectness:
    """Tests for Excel workbook generation."""

    def test_excel_generates_valid_bytes(self):
        """Generated bytes must begin with XLSX/OOXML magic marker (PK zip)."""
        ledger = [
            {"code": "1001", "name": "Tuition Receivable", "type": "Asset", "debit": 50000, "credit": 0},
        ]
        result = generate_financial_ledger_excel(ledgers_data=ledger)
        assert isinstance(result, bytes)
        assert len(result) > 0
        assert result[:2] == b"PK"  # XLSX is a ZIP archive

    def test_excel_handles_empty_ledger(self):
        """Excel generation must not crash with empty ledger data."""
        result = generate_financial_ledger_excel(ledgers_data=[])
        assert isinstance(result, bytes)
        assert result[:2] == b"PK"


class TestConcurrentGeneration:
    """Ensures no data mixing when generating reports concurrently."""

    def test_concurrent_pdf_generation_produces_distinct_outputs(self):
        """
        Generates multiple PDFs and verifies each produces
        unique output (no identical byte streams despite different data).
        """
        students = [
            ("Student Alpha", 90.0, "A"),
            ("Student Beta", 85.0, "B+"),
            ("Student Gamma", 78.0, "C"),
        ]
        results = []
        for name, attendance, grade in students:
            sabaq = [{"date": "2026-08-01", "juz_number": 1, "page_start": 1, "page_end": 5, "grade": grade}]
            pdf_bytes = generate_progress_report_pdf(
                student_name=name,
                attendance=attendance,
                grade=grade,
                sabaq_list=sabaq,
            )
            results.append((name, pdf_bytes))

        # All PDFs should be valid
        for name, pdf_bytes in results:
            assert pdf_bytes[:5] == b"%PDF-"
            assert len(pdf_bytes) > 100

        # All PDFs should be distinct (different content → different bytes)
        byte_sets = [pdf_bytes for _, pdf_bytes in results]
        for i in range(len(byte_sets)):
            for j in range(i + 1, len(byte_sets)):
                assert byte_sets[i] != byte_sets[j], f"PDFs {i} and {j} should differ"
