@echo off
cd "E:\Huffathul Hifaaz_asl\apps\internal-erp"
echo Installing Prisma...
call npm install prisma --save-dev
call npm install @prisma/client
echo Generating Prisma Client...
call npx prisma generate
echo Pushing Database Schema to SQLite...
call npx prisma db push --accept-data-loss
echo Seeding Database...
node prisma/seed.js
echo DATABASE READY
