@echo off
cd "E:\Huffathul Hifaaz_asl\apps\internal-erp"
echo Downgrading Prisma to v5 for schema compatibility...
call npm install prisma@5 @prisma/client@5 --save
echo Generating Prisma Client...
call npx prisma generate
echo Pushing Database Schema to SQLite...
call npx prisma db push --accept-data-loss
echo Seeding Database...
node prisma/seed.js
echo DATABASE READY
