-- =============================================================================
-- SUFFAT-UL HUFFAZ ERP & LMS - DORMANT EDGE MESH SCHEMA INTEGRATION
-- =============================================================================
-- File: dormant-edge-sync-migrations.sql
-- Description: Database migrations for Phase 16 (Local Hardware Mesh & Multi-Master
--              Offline Sync). These tables are designed to remain DORMANT in the 
--              PostgreSQL database from Day One, consuming zero active computational
--              overhead, but ready to be activated dynamically for remote, offline
--              centers.
-- Database Target: PostgreSQL 16
-- Multi-Tenancy Engine: Strict Row-Level Security (RLS) Isolated
-- =============================================================================

BEGIN;

-- -----------------------------------------------------------------------------
-- 1. EXTENSIONS & ENUMS
-- -----------------------------------------------------------------------------
-- Ensure cryptographic extension is present for signature and key checks
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- Enums representing the state of physical edge hardware deployment
DO $$ BEGIN
    CREATE TYPE edge_node_status AS ENUM ('DORMANT', 'ACTIVE', 'DEGRADED', 'OFFLINE');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
    CREATE TYPE sync_payload_status AS ENUM ('PENDING', 'PROCESSING', 'SYNCHRONIZED', 'FAILED_CONFLICT', 'FAILED_CORRUPT');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
    CREATE TYPE network_link_type AS ENUM ('SATELLITE', 'CELLULAR', 'BROADBAND', 'OFFLINE_PHYSICAL');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

-- -----------------------------------------------------------------------------
-- 2. TABLE DEFINITIONS
-- -----------------------------------------------------------------------------

-- A. Tenant Edge Nodes Table
-- Stores configurations for physical mini-servers / Raspberry Pi 5 nodes deployed on-premises.
CREATE TABLE IF NOT EXISTS tenant_edge_nodes (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id UUID NOT NULL, -- Direct tenant mapping for multi-tenant isolation
    branch_id UUID NOT NULL, -- Associated branch/campus
    node_identifier VARCHAR(100) UNIQUE NOT NULL, -- e.g., 'EDGENODE-KL-04'
    status edge_node_status DEFAULT 'DORMANT'::edge_node_status, -- Starts dormant!
    wireguard_public_key VARCHAR(128) NULL, -- Cryptographic peer handshake key
    local_ip_range CIDR NULL, -- On-prem local network CIDR blocks
    uplink_type network_link_type DEFAULT 'BROADBAND'::network_link_type,
    
    -- Live hardware telemetry metrics (JSONB fields keep dynamic logs scalable)
    hardware_specs JSONB DEFAULT '{
        "cpu_cores": 4,
        "total_ram_mb": 8192,
        "flash_storage_gb": 128
    }'::jsonb,
    live_telemetry JSONB DEFAULT '{
        "cpu_usage_pct": 0,
        "ram_usage_pct": 0,
        "disk_free_pct": 100,
        "core_temp_celsius": 0.0,
        "wireguard_handshake_latency_ms": null
    }'::jsonb,

    last_heartbeat TIMESTAMP WITH TIME ZONE NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- B. Edge Sync Queue Table
-- Manages incoming encrypted binary payload packages captured from local edge nodes.
CREATE TABLE IF NOT EXISTS edge_sync_queue (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id UUID NOT NULL, -- Direct tenant mapping for multi-tenant isolation
    node_id UUID NOT NULL REFERENCES tenant_edge_nodes(id) ON DELETE CASCADE,
    
    sequence_number BIGINT NOT NULL, -- Incremental mutation index verified for in-order replication
    protobuf_payload BYTEA NOT NULL, -- Compressed, serialized, and AES-256 encrypted payload packet
    payload_hash CHAR(64) NOT NULL, -- SHA-256 validation checksum of the raw payload
    client_signature VARCHAR(128) NOT NULL, -- Ed25519 authorization signature generated by edge node
    
    status sync_payload_status DEFAULT 'PENDING'::sync_payload_status,
    retry_count INT DEFAULT 0,
    failure_log TEXT NULL,
    
    synchronized_at TIMESTAMP WITH TIME ZONE NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- C. Local Cache Manifest Table
-- Tracks active cache indexes pushed to nodes to prevent redundant payload transmission.
CREATE TABLE IF NOT EXISTS local_cache_manifest (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id UUID NOT NULL,
    node_id UUID NOT NULL REFERENCES tenant_edge_nodes(id) ON DELETE CASCADE,
    cached_table VARCHAR(100) NOT NULL, -- Name of cached table (e.g., 'academic_records')
    last_known_hash CHAR(64) NOT NULL, -- Last matched checksum for cache sync checks
    total_records INT DEFAULT 0,
    
    last_validated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- -----------------------------------------------------------------------------
-- 3. INDEX OPTIMIZATIONS
-- -----------------------------------------------------------------------------
-- High-concurrency indices designed to minimize queue traversal times
CREATE INDEX IF NOT EXISTS idx_edge_nodes_tenant ON tenant_edge_nodes(tenant_id);
CREATE INDEX IF NOT EXISTS idx_edge_nodes_branch ON tenant_edge_nodes(branch_id);
CREATE INDEX IF NOT EXISTS idx_sync_queue_node_seq ON edge_sync_queue(node_id, sequence_number DESC);
CREATE INDEX IF NOT EXISTS idx_sync_queue_status ON edge_sync_queue(status) WHERE status = 'PENDING'::sync_payload_status;
CREATE INDEX IF NOT EXISTS idx_cache_manifest_node ON local_cache_manifest(node_id);

-- -----------------------------------------------------------------------------
-- 4. ROW-LEVEL SECURITY (RLS) POLICIES
-- -----------------------------------------------------------------------------
-- Enable RLS across all new tables to keep tenant isolation absolute.
ALTER TABLE tenant_edge_nodes ENABLE ROW LEVEL SECURITY;
ALTER TABLE edge_sync_queue ENABLE ROW LEVEL SECURITY;
ALTER TABLE local_cache_manifest ENABLE ROW LEVEL SECURITY;

-- Dynamic isolation policy: resolves tenancy context at runtime
DO $$ BEGIN
    DROP POLICY IF EXISTS tenant_edge_nodes_rls ON tenant_edge_nodes;
    CREATE POLICY tenant_edge_nodes_rls ON tenant_edge_nodes
        FOR ALL
        USING (tenant_id = current_setting('app.current_tenant_id', true)::uuid);
EXCEPTION
    WHEN undefined_object THEN null;
END $$;

DO $$ BEGIN
    DROP POLICY IF EXISTS edge_sync_queue_rls ON edge_sync_queue;
    CREATE POLICY edge_sync_queue_rls ON edge_sync_queue
        FOR ALL
        USING (tenant_id = current_setting('app.current_tenant_id', true)::uuid);
EXCEPTION
    WHEN undefined_object THEN null;
END $$;

DO $$ BEGIN
    DROP POLICY IF EXISTS local_cache_manifest_rls ON local_cache_manifest;
    CREATE POLICY local_cache_manifest_rls ON local_cache_manifest
        FOR ALL
        USING (tenant_id = current_setting('app.current_tenant_id', true)::uuid);
EXCEPTION
    WHEN undefined_object THEN null;
END $$;

-- -----------------------------------------------------------------------------
-- 5. TRIGGER AUTOMATIONS
-- -----------------------------------------------------------------------------
-- Automatically refresh update timestamps on modification.
CREATE OR REPLACE FUNCTION refresh_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trigger_update_edge_nodes_timestamp ON tenant_edge_nodes;
CREATE TRIGGER trigger_update_edge_nodes_timestamp
    BEFORE UPDATE ON tenant_edge_nodes
    FOR EACH ROW
    EXECUTE FUNCTION refresh_updated_at_column();

DROP TRIGGER IF EXISTS trigger_update_cache_manifest_timestamp ON local_cache_manifest;
CREATE TRIGGER trigger_update_cache_manifest_timestamp
    BEFORE UPDATE ON local_cache_manifest
    FOR EACH ROW
    EXECUTE FUNCTION refresh_updated_at_column();

-- -----------------------------------------------------------------------------
-- 6. SYSTEM DORMANT COMMENTARY (METADATA DOCUMENTATION)
-- -----------------------------------------------------------------------------
COMMENT ON TABLE tenant_edge_nodes IS 'DORMANT ENGINE: Configuration store for Raspberry Pi 5 node clusters. Keep status set to DORMANT unless rural deployment is toggled.';
COMMENT ON TABLE edge_sync_queue IS 'DORMANT ENGINE: Receives, holds, and validates serialized Protobuf data frames transmitted by active physical nodes.';
COMMENT ON TABLE local_cache_manifest IS 'DORMANT ENGINE: Sync registry tracking the revision status of client-side cache layers at edge locations.';

COMMIT;
-- =============================================================================
-- END OF MIGRATION SCRIPT
-- =============================================================================
