groups:
- name: SuffatErpSLA_Alerts
  rules:
  - alert: HighErrorRate
    expr: job:request_error_rate{job="core-backend"} > 0.05
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "High API Error Rate Detected (>5%)"
      description: "The core-backend API has experienced >5% HTTP 5xx responses for the last 1 minute."

  - alert: PgBouncerPoolSaturation
    expr: pgbouncer_pools_client_waiting_connections > 50
    for: 2m
    labels:
      severity: warning
    annotations:
      summary: "Database Connection Pool Saturated"
      description: "More than 50 clients are waiting for a Postgres connection. Execute Runbook: pg_pool_saturated.md."
